# Generated by Django 4.0 on 2021-12-19 11:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('fio', models.CharField(max_length=150)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('published', models.DateField(auto_now_add=True)),
                ('edited', models.DateField(auto_now=True)),
                ('tel_num', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['published'],
            },
        ),
    ]
