# Generated by Django 4.0 on 2021-12-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crm', '0002_remove_client_email_remove_client_tel_num_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
